In [1]:
import numpy as nm

# numpy is faster then list because it contains array which cover continuous space in memory

# creating array from list 

In [3]:
import numpy as np


In [4]:
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


# creating array from tuple

In [6]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


# creating 1 d array

In [2]:
import numpy as np

In [6]:
n = np.array([1,2,3,4])
print(type(n))

<class 'numpy.ndarray'>


# creating 2d array

n1 = np.array([[1,2,3],[4,5,6]])
print(type(n1))

# creating 3d array

In [9]:
n2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(type(n2))

<class 'numpy.ndarray'>


# creating float type array

In [13]:
n3 = np.array([""3],dtype = float)
n3

array([1., 2., 3.])

In [18]:
n4 = np.array([1,3,5,6],dtype = float)
n4

array([1., 3., 5., 6.])

# .arange() function

In [21]:
n5 = np.arange(1,11,2)
n5

array([1, 3, 5, 7, 9])

In [22]:
n6 = np.arange(1,5)
n6

array([1, 2, 3, 4])

# .reshape() function  

In [24]:
n7 = np.arange(1,10).reshape(3,3)
n7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## reshape function mai aap jo bhi array ka size aap pass krte ho unka product must be equal to number of elements in range 

 # .ones() , .zeros() and .random.random()

## .ones() - ye use hota hai 1 number ka matrix bnane k liye 
## .zeros - ye use hota hai 0 ka matrix bnane k liye 
## .random() - ye use hota hai 0 se 1 k beech  ka random number uthakar matrix bnana 

In [27]:
m = np.ones((3,4))
m

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
m1 = np.zeros((2,5))
m1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
m2 = np.random.random((3,3))
m2

array([[0.42194428, 0.30938686, 0.96194287],
       [0.46220324, 0.97619785, 0.20995422],
       [0.34659068, 0.14026775, 0.64734961]])

# .linspace() , .identity()

In [35]:
m4 = np.linspace(-10,10,10)
m4

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

### isme pahla start hai dusra end and third number of points hai jitne chaiye 

In [37]:
m8 = np.identity(3)
m8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### ye identity matrix form krta hai utna jitna size aap dete ho

# ye sab attributes hai

In [48]:
m10 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
m10
m10.ndim


3

In [49]:
m10.shape

(1, 3, 3)

In [50]:
m10.size

9

## ye batata hai ek element kitna size cover kr raha hai memory mai in (bytes)

In [51]:
m10.itemsize

8

# changing datatypes

In [56]:
m10.dtype

dtype('int64')

In [67]:
m10 = m10.astype(np.int32)
m10

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)

In [68]:
print(m10.dtype)

int32


# array operations

# arithemetic operations

In [69]:
m10

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)

In [70]:
m10 * 2

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]], dtype=int32)

In [71]:
m10 ** 2

array([[[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]], dtype=int32)

# relational operators

In [72]:
m10

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)

In [73]:
m10 > 5

array([[[False, False, False],
        [False, False,  True],
        [ True,  True,  True]]])

In [74]:
m10 == 5

array([[[False, False, False],
        [False,  True, False],
        [False, False, False]]])

In [75]:
m10 >= 8

array([[[False, False, False],
        [False, False, False],
        [False,  True,  True]]])

In [76]:
m10 <= 6

array([[[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]]])

# Array Functions

In [78]:
a1 = np.random.random((3,3))
a1 = a1 * 100
a1

array([[90.35952881, 67.64481417,  3.12351371],
       [84.98150773, 63.45877174, 95.08073364],
       [39.60053688, 84.23034086,  2.99915105]])

# min / max / sum / prod

## axis -> 1 rows axis -> 0 column

In [81]:
np.min(a1,axis = 1)

array([ 3.12351371, 63.45877174,  2.99915105])

In [82]:
np.max(a1,axis = 0)

array([90.35952881, 84.23034086, 95.08073364])

In [83]:
np.sum(a1,axis = 1)

array([161.1278567 , 243.52101312, 126.83002879])

In [84]:
np.prod(a1,axis = 1)

array([ 19092.02009557, 512753.48181118,  10003.86842246])

# mean / mode / median 

In [85]:
np.mean(a1,axis = 1)

array([53.70928557, 81.17367104, 42.27667626])

In [86]:
np.median(a1,axis = 0)

array([84.98150773, 67.64481417,  3.12351371])

# log and exponent function

In [87]:
np.exp(a1)

array([[1.74841592e+39, 2.38654443e+29, 2.27260925e+01],
       [8.07234792e+36, 3.62906207e+27, 1.96353188e+41],
       [1.57868196e+17, 3.80866036e+36, 2.00684925e+01]])

In [88]:
np.log(a1)

array([[4.50379648, 4.21427069, 1.13895856],
       [4.44243368, 4.15039043, 4.55472636],
       [3.67884268, 4.4335552 , 1.09832926]])

# round / floor / ceil  

In [91]:
np.round(a1)

array([[90., 68.,  3.],
       [85., 63., 95.],
       [40., 84.,  3.]])

In [92]:
np.floor(a1)

array([[90., 67.,  3.],
       [84., 63., 95.],
       [39., 84.,  2.]])

In [95]:
np.ceil(a1)

array([[91., 68.,  4.],
       [85., 64., 96.],
       [40., 85.,  3.]])

## floor: Always pushes the number down to the next whole integer. It completely ignores how large the decimal part is. For example, 4.9 becomes 4.
## ceil: Always pushes the number up to the next whole integer. Even a tiny decimal forces the jump. For example, 4.1 becomes 5.
## round: Automatically rounds to the nearest whole integer based on the decimal. It goes up if the decimal is .5 or higher, and down if it is lower.

# indexing and slicing

In [98]:

arr = np.array([5, 12, 19, 26, 33, 40, 47, 54])
arr

array([ 5, 12, 19, 26, 33, 40, 47, 54])

In [101]:
arr[5]

np.int64(40)

In [102]:
arr[1:5]

array([12, 19, 26, 33])

In [104]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
arr1[1,1]

np.int64(4)

In [107]:
arr1[0:2,1:3]

array([[1, 2],
       [4, 5]])

In [115]:
arr2 = np.arange(18).reshape((2,3,3))
arr2[1,1,1]

np.int64(13)

In [118]:
arr2[:1,1:3,:2]

array([[[3, 4],
        [6, 7]]])

# iterating

In [119]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [120]:
arr2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [122]:
arr

array([ 5, 12, 19, 26, 33, 40, 47, 54])

In [123]:
for i in arr:
    print(i)

5
12
19
26
33
40
47
54


### nditer() - ye pahle multidimensional array ko 1d array 9mai convert krta hai fir element print kr do

In [127]:
for i in np.nditer(arr2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


# transpose

In [136]:
np.transpose(arr2)

array([[[ 0,  9],
        [ 3, 12],
        [ 6, 15]],

       [[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]]])

# ravel - ye aapke array ko 1d mai convert kr deta hai

In [137]:
np.ravel(arr2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

# Stacking

In [140]:
a = np.arange(1,10).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
b = np.arange(10,19).reshape((3,3))
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [144]:
np.hstack((a,b))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [145]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# splitting

In [146]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [148]:
np.hsplit(a,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [149]:
np.vsplit(a,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

# how numpy array is faster then the python list

In [6]:
# this is python list
a = [ i for i in range(10000000)]
b = [ i for i in range(10000000,20000000)]

c = []
import time 
start = time.time()
for i in range(10000000):
    c.append(a[i] + b[i])
print(time.time() - start)

7.552225351333618


In [11]:
# now numpy array
import numpy as np
a = np.arange(10000000)

b = np.arange(10000000,20000000)

start = time.time()
c = a+b
print(time.time() - start)




0.6891751289367676


### like this numpy array takes less time to to append element in list

# Now on the basis of memory

In [13]:
aa = [i for i in range(10000000)]
import sys
sys.getsizeof(aa)

89095160

In [18]:
bb = np.arange(10000000)
sys.getsizeof(bb)
bb = bb.astype(np.int32)
sys.getsizeof(bb)

40000112

### ye yah pr size reduce kr diya

### basically numpy array is far better then the python list because it takes less time to execute nad take less space


# advance indexing

## fancy indexing

In [21]:
arp = np.arange(24).reshape((6,4))
arp

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
arp[[0,3,5]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [23]:
arp[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

# Boolean indexing

In [25]:
axp = np.random.randint(1,100,24).reshape(6,4)
axp

array([[91, 39, 48, 84],
       [13, 90, 71, 32],
       [82, 99, 58, 75],
       [92, 84, 30, 41],
       [48, 50, 29, 93],
       [43, 40,  4, 68]], dtype=int32)

In [26]:
# number divisible by 2
axp[axp%2 == 0]

array([48, 84, 90, 32, 82, 58, 92, 84, 30, 48, 50, 40,  4, 68],
      dtype=int32)

In [35]:
# number greater then 50 and divisible by 2
axp[(axp%2 == 0) & (axp>50)]

array([84, 90, 82, 58, 92, 84, 68], dtype=int32)

In [36]:
# find the number which is divisible by 7
axp[axp % 7 == 0]

array([91, 84, 84], dtype=int32)